from pathlib import Path
from typing import Any, Mapping, Literal
import numpy as np
from .run import Run
from .summary import RunSummary
from .distributions import MolarMassDistribution, MassDistribution, ChainLengthDistribution, DistributionGroup
from .sec import SECDistribution

class StorageChains:
    n_records: int
    n_chains: int
    dp: np.ndarray
    count: np.ndarray
    composition: Any
    component_count: np.ndarray
    def dp_counts(self) -> Any: ...
    def mass_counts(self, *, mass_model: str | None = ...) -> Any: ...
    def cld(self, *, weighting: str = ..., mass_model: str | None = ...) -> ChainLengthDistribution: ...
    def mass_distribution(self, *, weighting: str = ..., mass_model: str | None = ...) -> MassDistribution: ...
    def mwd(self, *, mass_model: str | None = ...) -> MolarMassDistribution: ...
    def sec(self, *, sigma_log10M: float, mass_model: str | None = ..., step_log10M: float | None = ...) -> SECDistribution: ...
    def moments(self, *, mass_model: str | None = ...) -> Any: ...
    def cld_series(self, *, series: Any, weighting: str = ..., normalization: str = ..., mass_model: str | None = ...) -> DistributionGroup: ...
    def mwd_series(self, *, series: Any, normalization: str = ..., mass_model: str | None = ...) -> DistributionGroup: ...
    def where_count(self, monomer: str, *, min: int | None = ..., max: int | None = ...) -> "StorageChains": ...
    def where_fraction(self, monomer: str, *, min: float | None = ..., max: float | None = ...) -> "StorageChains": ...
    def where_component_count(self, *, min: int | None = ..., max: int | None = ...) -> "StorageChains": ...
    def where_components(self, components: Any, *, exact: bool = ...) -> "StorageChains": ...
    def composition_by_dp(self, *, bins: Any = ...) -> Any: ...
    def composition_dp_map(self, monomer: str, *, dp_bins: Any = ..., fraction_bins: Any = ...) -> Any: ...
    def composition_mass_map(self, monomer: str, *, mass_model: str = ..., mass_bins: Any = ..., fraction_bins: Any = ...) -> Any: ...
    def composition_map(self, x: str, y: str, *, bins: Any = ...) -> Any: ...
    def component_classes(self) -> Any: ...
    def dyads_by_dp(self, *, bins: Any = ...) -> Any: ...
    def triads_by_composition(self, monomer: str, *, bins: Any = ...) -> Any: ...
    def block_count(self, monomer: str | None = ..., *, progress: Any = ...) -> np.ndarray: ...
    def junction_positions(self, left: str, right: str) -> tuple[tuple[int, ...], ...]: ...
    def junction_position(self, left: str, right: str) -> np.ndarray: ...

class StorageSnapshot:
    snapshot_id: int
    t: float
    event: int
    sid: int
    state: Any
    kmc_volume: float
    volume: float
    moles: Mapping[str, float]
    chains: StorageChains
    moments: Any
    channels: Any
    firings: Any
    copolymerization: Any
    kinetics: Any
    def dp_counts(self, *, pool: Any = ...) -> Any: ...
    def mass_counts(self, *, pool: Any = ..., mass_model: str | None = ...) -> Any: ...
    def mass_distribution(self, *, pool: Any = ..., weighting: str = ..., mass_model: str | None = ...) -> MassDistribution: ...
    def mwd(self, *, pool: Any = ..., mass_model: str | None = ...) -> MolarMassDistribution: ...
    def mwd_series(self, *, series: Any, normalization: str = ..., mass_model: str | None = ...) -> DistributionGroup: ...
    def cld(self, *, pool: Any = ..., weighting: str = ..., mass_model: str | None = ...) -> ChainLengthDistribution: ...
    def cld_series(self, *, series: Any, weighting: str = ..., normalization: str = ..., mass_model: str | None = ...) -> DistributionGroup: ...
    def sec(self, *, pool: Any = ..., sigma_log10M: float, mass_model: str | None = ..., step_log10M: float | None = ...) -> SECDistribution: ...
    def info(self) -> str: ...

class StorageRun(Run):
    path: Path
    t: np.ndarray
    event: np.ndarray
    sid: np.ndarray
    kmc_volume: np.ndarray
    volume: np.ndarray
    c0: Mapping[str, float]
    count0: Mapping[str, int]
    moles0: Mapping[str, float]
    feeds: Any
    feed_events: Any
    balance: Any
    snapshots: Any
    first: StorageSnapshot
    last: StorageSnapshot
    final: StorageSnapshot
    snapshots_with_chains: tuple[StorageSnapshot, ...]
    first_with_chains: StorageSnapshot
    last_with_chains: StorageSnapshot
    state: Any
    chains: StorageChains
    moments: Any
    channels: Any
    firings: Any
    copolymerization: Any
    microstructure: Any
    kinetics: Any
    actions: Any
    diagnostics: Any
    raw: Any
    output_status: Any
    validation: Any
    monomers: Mapping[str, Mapping[str, Any]]
    endgroups: Mapping[str, Mapping[str, Any]]
    chain_count: Any
    plot: Any
    conv: Any
    conc: Any
    moles: Any
    k: Any
    F: Any
    temp: np.ndarray
    def at_snapshot(self, snapshot_id: int) -> StorageSnapshot: ...
    def at_time(self, time: float, *, method: str = ...) -> StorageSnapshot: ...
    def at_event(self, event: int, *, method: str = ...) -> StorageSnapshot: ...
    def at_conversion(self, conversion: float, *, monomer: str | None = ..., method: str = ...) -> StorageSnapshot: ...
    def at_temperature(self, temperature: float) -> tuple[StorageSnapshot, ...]: ...
    def dp_counts(self, *, snapshot: Any = ..., pool: Any = ...) -> Any: ...
    def mass_counts(self, *, snapshot: Any = ..., pool: Any = ..., mass_model: str | None = ...) -> Any: ...
    def mass_distribution(self, *, snapshot: Any = ..., pool: Any = ..., weighting: str = ..., mass_model: str | None = ...) -> MassDistribution: ...
    def mwd(self, *, snapshot: Any = ..., pool: Any = ..., mass_model: str | None = ...) -> MolarMassDistribution: ...
    def mwd_series(self, *, snapshot: Any = ..., series: Any, normalization: str = ..., mass_model: str | None = ...) -> DistributionGroup: ...
    def cld(self, *, snapshot: Any = ..., pool: Any = ..., weighting: str = ..., mass_model: str | None = ...) -> ChainLengthDistribution: ...
    def cld_series(self, *, snapshot: Any = ..., series: Any, weighting: str = ..., normalization: str = ..., mass_model: str | None = ...) -> DistributionGroup: ...
    def sec(self, *, snapshot: Any = ..., pool: Any = ..., sigma_log10M: float, mass_model: str | None = ..., step_log10M: float | None = ...) -> SECDistribution: ...
    def validate(self, *, strict: bool = ...) -> Any: ...
    def refresh(self) -> "StorageRun": ...
    def mass_audit(self, *, tolerance: float = ..., snapshot: Any = ..., mass_model: str | None = ...) -> Any: ...
    def summary(self, path: str | Path | None = ...) -> RunSummary: ...
    def info(self) -> str: ...
