from pathlib import Path
from typing import Sequence, Any

class Runs(Sequence[Any]):
    root: Path
    @property
    def sweep_variables(self) -> tuple[str, ...]: ...
    def __getattr__(self, name: str) -> Any: ...
    def __dir__(self) -> list[str]: ...
    def match(self, pattern: str) -> "Runs": ...
    def by_path(self, path: str | Path) -> Any: ...
    def filter(self, **kwargs: Any) -> "Runs": ...
    @property
    def completed(self) -> "Runs": ...
    @property
    def failed(self) -> "Runs": ...
    @property
    def interrupted(self) -> "Runs": ...
    def pack(self, *, key: str | None = ..., **fields: Any) -> dict[str, dict[str, Any]]: ...
    def sweep(self, *variables: str) -> "Runs": ...
    def model_diff(self, *, include_same: bool = ...) -> Any: ...
    def info(self, max_rows: int = ...) -> str: ...
