#!/usr/bin/env python3
"""Generate the marked table of contents in Markdown documents."""
from __future__ import annotations

import argparse
import re
from pathlib import Path

START = "<!-- TOC:START -->"
END = "<!-- TOC:END -->"
GENERATED = "<!-- Generated by scripts/update_markdown_toc.py; do not edit by hand. -->"


def slug(text: str) -> str:
    text = re.sub(r"[`*_~]", "", text).strip().lower()
    text = re.sub(r"[^\w\- ]", "", text, flags=re.UNICODE)
    return re.sub(r"[\s-]+", "-", text).strip("-")


def headings(text: str) -> list[tuple[int, str]]:
    result: list[tuple[int, str]] = []
    in_fence = False
    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = re.match(r"^(#{2,4})\s+(.+?)\s*$", line)
        if match:
            result.append((len(match.group(1)), match.group(2)))
    return result


def rendered(text: str) -> str:
    if START not in text or END not in text:
        raise ValueError(f"missing {START} / {END} markers")
    counts: dict[str, int] = {}
    lines = [START, GENERATED]
    for level, title in headings(text):
        base = slug(title)
        occurrence = counts.get(base, 0)
        counts[base] = occurrence + 1
        anchor = base if occurrence == 0 else f"{base}-{occurrence}"
        lines.append(f"{'  ' * (level - 2)}- [{title}](#{anchor})")
    lines.append(END)
    block = "\n".join(lines)
    return re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        lambda _: block,
        text,
        count=1,
        flags=re.DOTALL,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="+", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[Path] = []
    for path in args.paths:
        original = path.read_text(encoding="utf-8")
        updated = rendered(original)
        if updated == original:
            continue
        if args.check:
            stale.append(path)
        else:
            path.write_text(updated, encoding="utf-8")
    if stale:
        for path in stale:
            print(f"stale table of contents: {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
